// Component exports for easy importing
export { ErrorBoundary, PageErrorFallback } from './ErrorBoundary'
export { CategoryShape, RenderShape } from './CategoryShape'
export { FloatingShapes } from './FloatingShapes'
export { IslandNav } from './IslandNav'
export { AuthProvider, useAuth } from './AuthProvider'
export type { Profile } from './AuthProvider'
export { SignInForm } from './SignInForm'
export { Footer } from './Footer'
export { Hero } from './Hero'
export { CommandBox } from './CommandBox'
export { InstallSection } from './InstallSection'
export { SkillCard } from './SkillCard'
export { CategoryFilter } from './CategoryFilter'
export { SearchInput } from './SearchInput'
export { KeyboardShortcutsHelp } from './KeyboardShortcutsHelp'
export { SkillCardSkeleton } from './SkillCardSkeleton'
export { TaskInput } from './TaskInput'
export { SkillRecommendations } from './SkillRecommendations'
export { AssistantIcon } from './AssistantIcon'
export { AssistantBadge } from './AssistantBadge'
export { CompatibilityMatrix } from './CompatibilityMatrix'
export { ShareButtons } from './ShareButtons'
export { VoteButton } from './VoteButton'
export { CompareButton } from './CompareButton'
export { SkillComments } from './SkillComments'
export { ComparisonBar } from './ComparisonBar'
export { AddToBundleButton } from './AddToBundleButton'
export { WorkflowBuilder } from './WorkflowBuilder'
export { WorkflowCanvas } from './WorkflowCanvas'
export { WorkflowNodeComponent } from './WorkflowNode'
export { WorkflowSidebar } from './WorkflowSidebar'
export { WorkflowCard } from './WorkflowCard'
export { BundleCard } from './BundleCard'
export { CodeBlock } from './CodeBlock'
export { FeaturedSkills } from './FeaturedSkills'
export { SkillOfTheDay } from './SkillOfTheDay'
