import matter from "gray-matter";
import manifest from "./docs-manifest.json" with { type: "json" };

/* Docs come from the committed docs-manifest.json (regenerated by
   scripts/docs-manifest.mjs on every build), not the filesystem: the
   Cloudflare Worker has no source tree at request time, so readdirSync
   and readFileSync here returned 500 on every docs route in production. */

const files: Record<string, string> = manifest.files;

export interface DocMeta {
  slug: string;
  title: string;
  description?: string;
  order?: number;
  category?: string;
  badge?: string;
}

function getAllMdxFiles(): string[] {
  return Object.keys(files);
}

export async function getAllDocs(): Promise<DocMeta[]> {
  const docs = getAllMdxFiles()
    .map((file) => {
      const slug = file.replace(/\.mdx$/, "");
      const { data } = matter(files[file]);

      return {
        slug,
        title: data.title || slug.split("/").pop()?.replace(/-/g, " ") || "",
        description: data.description,
        order: data.order || 999,
        category: data.category,
        badge: data.badge,
      };
    })
    .sort((a, b) => {
      // Sort by category first, then by order
      if (a.category !== b.category) {
        return (a.category || "").localeCompare(b.category || "");
      }
      return a.order - b.order;
    });

  return docs;
}

export async function getDocBySlug(slug: string) {
  if (!/^[a-z0-9-]+(?:\/[a-z0-9-]+)*$/.test(slug)) return null;
  const fileContents = files[`${slug}.mdx`];
  if (fileContents === undefined) {
    return null;
  }

  const { data, content } = matter(fileContents);

  return {
    slug,
    meta: data,
    content,
  };
}
