/**
 * Validates the committed content snapshots in src/data/*.json without any
 * network access. This is the portfolio's `prebuild`: it makes sure the
 * source tree that's about to be compiled actually has the shapes every
 * page expects, and fails the build loudly if a snapshot is missing or
 * malformed instead of shipping an empty/placeholder page silently.
 *
 * Local note snapshots are generated by scripts/build-notes.mjs before verification.
 * Refresh the npm version separately with `npm run content:refresh`.
 */
import { readFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { SNAPSHOTS } from './lib/content-sources.mjs'

const DEFAULT_DATA_DIR = join(dirname(fileURLToPath(import.meta.url)), '../src/data')

/**
 * @param {object} [options]
 * @param {string} [options.dataDir]
 * @param {typeof SNAPSHOTS} [options.sources]
 * @returns {string[]} one message per problem found, empty when everything is valid
 */
export function verifyContent({ dataDir = DEFAULT_DATA_DIR, sources = SNAPSHOTS } = {}) {
  const errors = []

  for (const source of sources) {
    const valueByFile = {}
    let readable = true

    for (const file of source.files) {
      const path = join(dataDir, file)
      if (!existsSync(path)) {
        errors.push(`${file}: missing`)
        readable = false
        continue
      }
      const text = readFileSync(path, 'utf8')
      try {
        valueByFile[file] = JSON.parse(text)
      } catch (err) {
        errors.push(`${file}: invalid JSON (${err instanceof Error ? err.message : String(err)})`)
        readable = false
      }
    }

    if (!readable) continue
    for (const message of source.validate(valueByFile)) errors.push(message)
  }

  return errors
}

function main() {
  const errors = verifyContent({})
  for (const message of errors) console.error(`[verify-content] ${message}`)
  if (errors.length > 0) {
    console.error(
      `[verify-content] ${errors.length} problem(s) found. Regenerate notes with "node scripts/build-notes.mjs"; refresh ui-meta with "npm run content:refresh".`
    )
    process.exit(1)
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main()
}
