/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/n3wthTheme.ts
 * Command: astryx theme build src/theme/n3wthTheme.ts --out src/theme/n3wth-theme.css
 * Generated: 2026-07-14T19:56:44.788Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const n3wthTheme: DefinedTheme;
