import { PageHeader, SiteSection, SiteDocSection, SiteDocList, SiteText } from '@n3wth/ui/site'
import { usePageMeta, buildWebPageSchema } from '../hooks/usePageMeta'
import { RouterLink } from '../components/RouterLink'

const TITLE = 'Terms of Service — n3wth'
const DESCRIPTION =
  "Terms of service for n3wth.com and They Won't Shut Up AI voice hotline."

export default function Terms() {
  usePageMeta(TITLE, DESCRIPTION, {
    ogImage: '/og-image.png',
    jsonLd: buildWebPageSchema({
      url: 'https://n3wth.com/terms',
      title: TITLE,
      description: DESCRIPTION,
      breadcrumbs: [
        { name: 'Home', url: 'https://n3wth.com/' },
        { name: 'Terms of Service', url: 'https://n3wth.com/terms' },
      ],
    }),
  })

  return (
    <section aria-label="Terms of Service">
      <PageHeader
        data-reveal
        align="center"
        className="site-content-gutter mx-auto max-w-3xl"
        title="Terms of Service"
        description={<>Last updated: September 2026</>}
      />

      <SiteSection data-reveal className="site-content-gutter mx-auto max-w-3xl">
        <SiteDocSection title="1. Acceptance">
          <SiteText>
            By using n3wth.com or calling the They Won&apos;t Shut Up hotline at{' '}
            <strong style={{ color: 'var(--ink)' }}>+1 (855) 580-0508</strong>, you agree to these
            terms. If you do not agree, do not use the service.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="2. Service Description">
          <SiteText>
            They Won&apos;t Shut Up is an AI voice hotline operated by n3wth.com. The service
            provides entertainment-oriented conversations with AI characters via telephone. The AI
            characters are fictional and powered by ElevenLabs Conversational AI technology.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="3. AI Disclosure">
          <SiteText>
            All voices and conversations on the hotline are generated by artificial intelligence.
            The characters are not real people. Conversations should not be relied upon for
            professional advice of any kind, including medical, legal, financial, or mental health
            guidance.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="4. SMS Messaging">
          <SiteText>
            By calling the hotline, you may opt in to receive SMS messages. See our{' '}
            <RouterLink href="/consent" className="link-underline">SMS Consent page</RouterLink> for
            full details on messaging terms, frequency, and how to opt out. Message and data rates
            may apply. Reply STOP to unsubscribe at any time. SMS privacy and retention are covered
            in the{' '}
            <RouterLink href="/privacy" className="link-underline">Privacy Policy</RouterLink>.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="Elsa and Billy assistant SMS">
          <SiteText>
            By texting START, HELLO, or a first message to Elsa at{' '}
            <strong style={{ color: 'var(--ink)' }}>+1 (415) 718-0992</strong> after reading the
            disclosures on{' '}
            <RouterLink href="/elsa" className="link-underline">https://n3wth.com/elsa</RouterLink>,
            or to Billy at <strong style={{ color: 'var(--ink)' }}>+1 (463) 258-8004</strong> after
            reading the disclosures on{' '}
            <RouterLink href="/billy" className="link-underline">https://n3wth.com/billy</RouterLink>,
            you agree to the messaging terms on that page.
            Message frequency varies. Message and data rates may apply. Reply STOP to unsubscribe.
            Reply HELP for help. SMS is optional and is not required to use n3wth.com or other site
            services. Privacy, retention, and California privacy rights for SMS are
            described in the{' '}
            <RouterLink href="/privacy" className="link-underline">Privacy Policy</RouterLink>.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="5. Acceptable Use">
          <SiteText>You agree not to:</SiteText>
          <SiteDocList
            items={[
              'Use the service for any unlawful purpose',
              'Attempt to disrupt or overload the service',
              'Record or redistribute calls without consent',
            ]}
          />
        </SiteDocSection>

        <SiteDocSection title="6. No Warranty">
          <SiteText>
            The service is provided &quot;as is&quot; without warranty of any kind. n3wth.com makes
            no guarantees regarding availability, accuracy, or suitability for any purpose.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="7. Limitation of Liability">
          <SiteText>
            n3wth.com shall not be liable for any damages arising from use of the service, including
            but not limited to reliance on AI-generated content.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="8. Changes">
          <SiteText>
            These terms may be updated at any time. Continued use of the service after changes
            constitutes acceptance of the updated terms.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="9. Contact">
          <SiteText>
            For questions about these terms, contact{' '}
            <a href="mailto:hey@n3wth.com" className="link-underline">hey@n3wth.com</a>.
          </SiteText>
        </SiteDocSection>
      </SiteSection>
    </section>
  )
}