import type { ReactNode } from 'react'
import { PageHeader, SiteSection, SiteHeading } from '@n3wth/ui/site'
import { usePageMeta, buildWebPageSchema } from '../hooks/usePageMeta'
import { RouterLink } from '../components/RouterLink'

const TITLE = 'Terms of Service — n3wth'
const DESCRIPTION =
  "Terms of service for n3wth.com and They Won't Shut Up AI voice hotline."

function Prose({ children }: { children: ReactNode }) {
  return (
    <p className="mt-3 text-base leading-relaxed" style={{ color: 'var(--ink-dim)' }}>
      {children}
    </p>
  )
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div className="mt-10 first:mt-0">
      <SiteHeading variant="item" level={2}>{title}</SiteHeading>
      {children}
    </div>
  )
}

function BulletList({ items }: { items: ReactNode[] }) {
  return (
    <ul className="mt-3 list-disc space-y-2 pl-5 text-base leading-relaxed" style={{ color: 'var(--ink-dim)' }}>
      {items.map((item, i) => (
        <li key={i}>{item}</li>
      ))}
    </ul>
  )
}

export default function Terms() {
  usePageMeta(TITLE, DESCRIPTION, {
    ogImage: '/og-image.png',
    jsonLd: buildWebPageSchema({
      url: 'https://n3wth.com/terms',
      title: TITLE,
      description: DESCRIPTION,
      breadcrumbs: [
        { name: 'Home', url: 'https://n3wth.com/' },
        { name: 'Terms of Service', url: 'https://n3wth.com/terms' },
      ],
    }),
  })

  return (
    <section aria-label="Terms of Service">
      <PageHeader
        data-reveal
        className="site-content-gutter"
        title="Terms of Service"
        description={<>Last updated: September 2026</>}
      />

      <SiteSection data-reveal className="site-content-gutter max-w-3xl">
        <Section title="1. Acceptance">
          <Prose>
            By using n3wth.com or calling the They Won&apos;t Shut Up hotline at{' '}
            <strong style={{ color: 'var(--ink)' }}>+1 (855) 580-0508</strong>, you agree to these
            terms. If you do not agree, do not use the service.
          </Prose>
        </Section>

        <Section title="2. Service Description">
          <Prose>
            They Won&apos;t Shut Up is an AI voice hotline operated by n3wth.com. The service
            provides entertainment-oriented conversations with AI characters via telephone. The AI
            characters are fictional and powered by ElevenLabs Conversational AI technology.
          </Prose>
        </Section>

        <Section title="3. AI Disclosure">
          <Prose>
            All voices and conversations on the hotline are generated by artificial intelligence.
            The characters are not real people. Conversations should not be relied upon for
            professional advice of any kind, including medical, legal, financial, or mental health
            guidance.
          </Prose>
        </Section>

        <Section title="4. SMS Messaging">
          <Prose>
            By calling the hotline, you may opt in to receive SMS messages. See our{' '}
            <RouterLink href="/consent" className="link-underline">SMS Consent page</RouterLink> for
            full details on messaging terms, frequency, and how to opt out. Message and data rates
            may apply. Reply STOP to unsubscribe at any time. SMS privacy and retention are covered
            in the{' '}
            <RouterLink href="/privacy" className="link-underline">Privacy Policy</RouterLink>.
          </Prose>
        </Section>

        <Section title="Elsa assistant SMS">
          <Prose>
            By texting <strong style={{ color: 'var(--ink)' }}>+1 (415) 718-0992</strong> or{' '}
            <strong style={{ color: 'var(--ink)' }}>+1 (415) 360-0751</strong> or
            opting in to Elsa SMS, you agree to the messaging terms on{' '}
            <RouterLink href="/elsa" className="link-underline">https://n3wth.com/elsa</RouterLink>.
            Message frequency varies. Message and data rates may apply. Reply STOP to unsubscribe.
            Reply HELP for help. Privacy, retention, and California privacy rights for SMS are
            described in the{' '}
            <RouterLink href="/privacy" className="link-underline">Privacy Policy</RouterLink>.
          </Prose>
        </Section>

        <Section title="5. Acceptable Use">
          <Prose>You agree not to:</Prose>
          <BulletList
            items={[
              'Use the service for any unlawful purpose',
              'Attempt to disrupt or overload the service',
              'Record or redistribute calls without consent',
            ]}
          />
        </Section>

        <Section title="6. No Warranty">
          <Prose>
            The service is provided &quot;as is&quot; without warranty of any kind. n3wth.com makes
            no guarantees regarding availability, accuracy, or suitability for any purpose.
          </Prose>
        </Section>

        <Section title="7. Limitation of Liability">
          <Prose>
            n3wth.com shall not be liable for any damages arising from use of the service, including
            but not limited to reliance on AI-generated content.
          </Prose>
        </Section>

        <Section title="8. Changes">
          <Prose>
            These terms may be updated at any time. Continued use of the service after changes
            constitutes acceptance of the updated terms.
          </Prose>
        </Section>

        <Section title="9. Contact">
          <Prose>
            For questions about these terms, contact{' '}
            <a href="mailto:hey@n3wth.com" className="link-underline">hey@n3wth.com</a>.
          </Prose>
        </Section>
      </SiteSection>
    </section>
  )
}
