-- Better Auth default schema (better-auth 1.7.5, SQLite/D1 dialect).
-- Mirrors the tables generated by better-auth's Kysely migration for the
-- default user/session/account/verification models (see
-- node_modules/@better-auth/core/dist/db/get-tables.mjs).
--
-- The magic-link plugin does not add tables; it stores issued tokens in the
-- core verification table via internalAdapter.createVerificationValue.
--
-- Timestamps: better-auth's D1 dialect stores dates as ISO 8601 TEXT strings
-- (adapter factory calls toISOString() when supportsDates is false, and the
-- Kysely D1/sqlite adapter sets supportsDates: false). TEXT here matches the
-- ISO created_at/updated_at TEXT columns used by 0002_app.sql.
-- Booleans are stored as INTEGER 0/1 by the adapter (supportsBooleans: false).
-- No column-level defaults: better-auth applies createdAt/updatedAt and
-- emailVerified defaults in the adapter, matching its generated migration.

CREATE TABLE IF NOT EXISTS user (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  emailVerified INTEGER NOT NULL,
  image TEXT,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS session (
  id TEXT PRIMARY KEY NOT NULL,
  expiresAt TEXT NOT NULL,
  token TEXT NOT NULL UNIQUE,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL,
  ipAddress TEXT,
  userAgent TEXT,
  userId TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS session_userId_idx ON session(userId);

CREATE TABLE IF NOT EXISTS account (
  id TEXT PRIMARY KEY NOT NULL,
  accountId TEXT NOT NULL,
  providerId TEXT NOT NULL,
  userId TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,
  accessToken TEXT,
  refreshToken TEXT,
  idToken TEXT,
  accessTokenExpiresAt TEXT,
  refreshTokenExpiresAt TEXT,
  scope TEXT,
  password TEXT,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS account_userId_idx ON account(userId);

CREATE TABLE IF NOT EXISTS verification (
  id TEXT PRIMARY KEY NOT NULL,
  identifier TEXT NOT NULL,
  value TEXT NOT NULL,
  expiresAt TEXT NOT NULL,
  createdAt TEXT NOT NULL,
  updatedAt TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON verification(identifier);

-- Durable rate limiting (better-auth rateLimit.storage = "database").
-- Rows appear only when rateLimit.storage is "database"; counters persist in
-- D1 so limits hold across requests/isolates.
CREATE TABLE IF NOT EXISTS rateLimit (
  id TEXT PRIMARY KEY NOT NULL,
  key TEXT NOT NULL UNIQUE,
  count INTEGER NOT NULL,
  lastRequest INTEGER NOT NULL
);
