import { withTheme } from '../components/withTheme'
import { PageHeader, SiteSection, SiteDocSection, SiteDocList, SiteText } from '@n3wth/ui/site'

function Terms() {

  return (
    <section aria-label="Terms of Service">
      <PageHeader
        data-reveal
        align="center"
        className="site-content-gutter mx-auto max-w-3xl"
        title="Terms of Service"
        description={<>Last updated: September 2026</>}
      />

      <SiteSection data-reveal className="site-content-gutter mx-auto max-w-3xl">
        <SiteDocSection title="1. Acceptance">
          <SiteText>
            By using n3wth.com or calling the They Won&apos;t Shut Up hotline at{' '}
            <strong style={{ color: 'var(--ink)' }}>+1 (855) 580-0508</strong>, you agree to these
            terms. If you do not agree, do not use the service.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="Elephant-Goldfish plugin">
          <SiteText>
            Elephant-Goldfish 0.1.0 is an independent Codex plugin adaptation by Oliver Newth.
            It is based on Dave Rensin&apos;s Elephant-Goldfish model and Vladyslav Shvedov&apos;s
            workflows. It is not an official release from those authors or OpenAI.
            The bundled MIT license governs use, copying, modification, and distribution of the
            plugin. Preserve its copyright and license notices. These site terms do not restrict
            the rights granted by that license.
          </SiteText>
          <SiteText>
            The plugin supplies instructions for brainstorming, requirements, feature design,
            bug diagnosis, and code review. Independent checks require fresh subagent support.
            AI output may be incomplete or wrong. Review proposed changes and run appropriate
            checks before relying on them. Use only repositories and data you are authorized to
            access. Codex and any selected integrations remain subject to their own terms,
            permissions, availability, and charges.
          </SiteText>
          <SiteText>
            The plugin is provided as is under the MIT license, without warranty. A review does
            not guarantee correctness or security. For support, email{' '}
            <a href="mailto:support@n3wth.com" className="link-underline">support@n3wth.com</a>.
            See the <a href="/privacy" className="link-underline">Privacy Policy</a>{' '}
            and <a href="/projects/elephant-goldfish" className="link-underline">project page</a>.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="2. Service Description">
          <SiteText>
            They Won&apos;t Shut Up is an AI voice hotline operated by n3wth.com. The service
            provides entertainment-oriented conversations with AI characters via telephone. The AI
            characters are fictional and powered by ElevenLabs Conversational AI technology.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="3. AI Disclosure">
          <SiteText>
            All voices and conversations on the hotline are generated by artificial intelligence.
            The characters are not real people. Conversations should not be relied upon for
            professional advice of any kind, including medical, legal, financial, or mental health
            guidance.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="4. SMS Messaging">
          <SiteText>
            By calling the hotline, you may opt in to receive SMS messages. See our{' '}
            <a href="/consent" className="link-underline">SMS Consent page</a> for
            full details on messaging terms, frequency, and how to opt out. Message and data rates
            may apply. Reply STOP to unsubscribe at any time. SMS privacy and retention are covered
            in the{' '}
            <a href="/privacy" className="link-underline">Privacy Policy</a>.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="Elsa and Billy assistant SMS">
          <SiteText>
            By texting START to Elsa at{' '}
            <strong style={{ color: 'var(--ink)' }}>+1 (463) 258-8004</strong> after reading the
            disclosures on{' '}
            <a href="/elsa" className="link-underline">https://n3wth.com/elsa</a>,
            or to Billy at <strong style={{ color: 'var(--ink)' }}>+1 (415) 718-0992</strong> after
            reading the disclosures on{' '}
            <a href="/billy" className="link-underline">https://n3wth.com/billy</a>,
            you agree to the messaging terms on that page.
            Message frequency varies. Message and data rates may apply. Reply STOP to unsubscribe.
            Reply HELP for help. SMS is optional and is not required to use n3wth.com or other site
            services. Privacy, retention, and California privacy rights for SMS are
            described in the{' '}
            <a href="/privacy" className="link-underline">Privacy Policy</a>.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="5. Acceptable Use">
          <SiteText>You agree not to:</SiteText>
          <SiteDocList
            items={[
              'Use the service for any unlawful purpose',
              'Attempt to disrupt or overload the service',
              'Record or redistribute calls without consent',
            ]}
          />
        </SiteDocSection>

        <SiteDocSection title="6. No Warranty">
          <SiteText>
            The service is provided &quot;as is&quot; without warranty of any kind. n3wth.com makes
            no guarantees regarding availability, accuracy, or suitability for any purpose.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="7. Limitation of Liability">
          <SiteText>
            n3wth.com shall not be liable for any damages arising from use of the service, including
            but not limited to reliance on AI-generated content.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="8. Changes">
          <SiteText>
            These terms may be updated at any time. Continued use of the service after changes
            constitutes acceptance of the updated terms.
          </SiteText>
        </SiteDocSection>

        <SiteDocSection title="9. Contact">
          <SiteText>
            For questions about these terms, contact{' '}
            <a href="mailto:hey@n3wth.com" className="link-underline">hey@n3wth.com</a>.
          </SiteText>
        </SiteDocSection>
      </SiteSection>
    </section>
  )
}

export default withTheme(Terms)
